class Config:
    SPOTIFY_CLIENT_ID = ''
    SPOTIFY_CLIENT_SECRET = ''
    SPOTIFY_REFRESH_TOKEN = ''

    TWITTER_API_CONSUMER_KEY = ''
    TWITTER_API_CONSUMER_SECRET = ''
    TWITTER_API_ACCESS_TOKEN = ''
    TWITTER_API_ACCESS_TOKEN_SECRET = ''
