name: Deploy to Amazon Lambda

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy lambda
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
        zip -r gorrion-telegram-bot.zip .

    - name: Deploy to AWS
      uses: appleboy/lambda-action@v0.1.9
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-2
        function_name: gorrion-telegram-bot
        zip_file: gorrion-telegram-bot.zip
