name: Deploy to Amazon Lambda

on:
  push:
    branches: [ telegram-bot ]

jobs:
  deploy:
    name: Deploy lambda
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        zip -r gorrion-telegram-bot.zip .

    - name: Deploy to AWS
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: eu-west-2
        function_name: gorrion-telegram-bot
        zip_file: gorrion-telegram-bot.zip

